name: 'Package Store'
title: null
description: ''
email: 'mail@kaikim.ru'
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: ''
    values:
      image: ''

webmaster_verifications:
  google: ''
  yandex: ''

author:
  name: 'Kai Kimera'
  url: 'https://kaikim.ru/'
locale: 'ru_RU'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
